# single positions
hug: [[0.0, 0.7335793379057367, -0.21923080734300773, -1.0316466675613283, -0.04120722363958612, -0.970490330571447, 1.3667847905292794]]

#wave1: [[1.5, -1, 0, 0, 0, 0, 0]]
wave1: [[1.69,1.19,-0.48,-2.09,-0.34,0.16,0.12]]
#wave2: [[1.5, -1, 0, -1, 0, 0, 0]]
wave2 : [[1.69, 1.19, -0.48, -2.61, -0.34, -0.38, -0.5]]
point2chest: [[-0.1, -1, 0, -1.4, 0, -1.5, 0]]
point2torso_low: [[-0.8, -1, 0, -1.4, -0.5, -1, 0]]
point2torso: [[1.519588366541383, 1.0853679019377138, -1.6425642656369035, -1.9734961451075483, -1.106207133206526, -1.5106697340636919, 1.7219418400176056]]
point2base: [[1.331511686346474, 1.0853679019377138, -1.6425468123443836, -1.4519044981490428, -1.6384801951872368, -1.2950692115648323, 0.9537526230448213]]
point2head: [[1.8957591802237208, 1.008974840577922, -1.819976984102127, -2.3907869159668724, -0.041713369122664476, -0.8099723992655284, 1.1903145498601329]]
point2camera: [[-0.49, -1.04, -0.2, -1.4, -0.3, -1.5, 0]]

count1: [[-0.2, -1.2, 1, 0, 0, 0, 0]]
count1a: [[-0.2, -1.2, 1, -0.4, 0 ,0 ,0]]
count2: [[-0.2, -1.35, 1, 0, 0, 0, 0]]
count2a: [[-0.2, -1.35, 1, -0.4, 0, 0, 0]]
count3: [[-0.2, -1.5, 1, 0, 0, 0, 0]]
count3a: [[-0.2, -1.5, 1, -0.4, 0, 0, 0]]
count4: [[-0.2, -1.65, 1, 0, 0, 0, 0]]

carry1: [[-1.3, -1, 0, -0.6, 0, 0, 0]]
carry2: [[-1.3, 0.5, 0, -2, 0, 0, 0]]

open: [[-0.4, -1.3, 1, -0.5, 0, 0, 0]]



pre_grasp: [[-0.09403834009745447, -0.30396654252733246, -0.29567622858035936, -1.5126070495334056, 0.5322381553956708, -0.6999817498048458, 0.8931722447080982]]

# trajectory
wave_hmi: [wave1, wave2, wave1, wave2, side]
count: [count1, count1a, count2, count2a, count3, count3a, count4]
draw_torso: [point2chest, point2torso_low, point2chest]
carry: [carry1, carry2, carry1]
